### ISSUE TITLE
Missing installation documentation

### ISSUE THREAD

**Issue by rossigee** [aquasecurity/vscode-tfsec#11]
How can I install this extension?

I'm using 'vscodium'. It doesn't appear in the extensions list, and there are no builds/releases of this repo I can see that i could download a 'vsix' file from. Where should I start?

**Comment by owenrumney** [comment]
Hey @rossigee - we've just added it to open-vsx.org (https://open-vsx.org/extension/tfsec/tfsec) which I believe VSCodium uses for its marketplace. 

I'll also add the vsix files as releases shortly

**Comment by owenrumney** [comment]
Hey @rossigee  - added a workflow for releases in github too
