### ISSUE TITLE
Ignore comments are, well, ignored

### ISSUE THREAD

**Issue by vanmash** [aquasecurity/vscode-tfsec#22]
**Describe the bug**
1. tfsec finds errors even though the ignore comment is present.
2. **ignore this issue** duplicates ignore comments

in this example azure-appservice-account-identity-registered is not set. tfsec ext. finds regardless of ignore commends and duplicates the comment 

```hcl
#tfsec:ignore:azure-appservice-require-client-cert
#tfsec:ignore:azure-appservice-php-version
#tfsec:ignore:azure-appservice-python-version
#tfsec:ignore:azure-appservice-account-identity-registered
#tfsec:ignore:azure-appservice-authentication-enabled
#tfsec:ignore:azure-appservice-account-identity-registered
resource "azurerm_app_service" "app1" {
  #tfsec:ignore:azure-appservice-require-client-cert
  name                    = "app-${var.PRODUCT}-${var.ENV}-api"

```

**Desktop (please complete the following information):**
 - OS: macOS 12.1
 - Tfsec Version v1.7.4
 - VSCode Version 1.63.2

**Comment by owenrumney** [comment]
@vanmash - this is an issue in tfsec - there will be a new release coming out shortly
